name: CICD

on:
  workflow_dispatch: 
    inputs:
      enviorements:
        description: This is a enviorements value wher this workflow rus
        default: dev
        required: true
        type: choice
        options:
          - dev
          - staging
          - main
      


jobs:

  code:
    runs-on: ubuntu-slim
    steps:
      - name: code
        run: echo "Code from GitHub"

  build:
    runs-on: ubuntu-22.04
    needs: code
    steps:
      - name: build continue-on-er
        run: echo "build ho gya"
