name: CICD

on:
 workflow_dispatch:
  inputs:
   environments:
    description: "This is an env"
    default: dev
    required: true
    type: choice
    options:
     - dev
     - main
     - staging

jobs:

  code:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        run: echo "code checkout ho gaya"

  run:
   runs-on: ubuntu-22.04
   steps:
     - name: run code
       run: echo "code run ho gaya"
     
     
